Repository astro-mood/FS, pull requests merged in 2025-01, with the labels that each got.

#4 FE setting
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/App.js
  src/main/frontend/src/components/layout/Header.jsx
  src/main/frontend/src/components/layout/Layout.jsx
  src/main/frontend/src/pages/AboutAll.jsx
  src/main/frontend/src/pages/AboutLogin.jsx
  src/main/frontend/src/pages/AnswerWorryBoard.jsx
  src/main/frontend/src/pages/AnswerWorryDetail.jsx
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/DiaryCalendar.jsx
  src/main/frontend/src/pages/Intro.jsx
  src/main/frontend/src/pages/Main.jsx
  src/main/frontend/src/pages/ModifyUser.jsx
  src/main/frontend/src/pages/MyDiary.jsx
  src/main/frontend/src/pages/MyWorry.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/WriteDiary.jsx
  src/main/frontend/src/pages/WriteWorry.jsx
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
  src/main/resources/static/static/css/main.f855e6bc.css.map
Labels: ⚙ Setting

#6 FE Layout setting
  src/main/frontend/src/App.css
  src/main/frontend/src/App.js
  src/main/frontend/src/App.test.js
  src/main/frontend/src/components/layout/Background.css
  src/main/frontend/src/components/layout/Background.jsx
  src/main/frontend/src/components/layout/ContentsArea.jsx
  src/main/frontend/src/components/layout/GlobalStyle.jsx
  src/main/frontend/src/components/layout/Header.jsx
  src/main/frontend/src/components/layout/HeaderLayout.jsx
  src/main/frontend/src/components/layout/Layout.jsx
  src/main/frontend/src/images/logo.png
  src/main/frontend/src/logo.svg
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/index.html
Labels: 🎨 Html&css

#8 백엔드 초기세팅 작업중
  .gitignore
  build.gradle
  src/main/java/com/astro/mood/MoodApplication.java
  src/main/java/com/astro/mood/config/DataSourceProperties.java
  src/main/java/com/astro/mood/config/JpaConfig.java
  src/main/java/com/astro/mood/config/JwtUtil_origin.java
  src/main/java/com/astro/mood/config/S3Config.java
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/config/WebConfig.java
  src/main/java/com/astro/mood/data/entity/diary/Diary.java
  src/main/java/com/astro/mood/data/entity/diary/DiaryComment.java
  src/main/java/com/astro/mood/data/entity/diary/DiaryEmotion.java
  src/main/java/com/astro/mood/data/entity/emotion/Emotion.java
  src/main/java/com/astro/mood/data/entity/emotion/EmotionAnalysis.java
  src/main/java/com/astro/mood/data/entity/emotion/Emotions.java
  src/main/java/com/astro/mood/data/entity/likes/Likes.java
  src/main/java/com/astro/mood/data/entity/user/User.java
  src/main/java/com/astro/mood/data/entity/user/UserToken.java
  src/main/java/com/astro/mood/data/entity/worry/Worry.java
  src/main/java/com/astro/mood/data/entity/worry/WorryComment.java
  src/main/java/com/astro/mood/data/repository/auth/AuthRepository.java
  src/main/java/com/astro/mood/security/jwt/JWTFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/security/jwt/JwtToken.java
  src/main/java/com/astro/mood/security/login/CustomOauth2UserDetails.java
  src/main/java/com/astro/mood/security/login/CustomUserDetails.java
  src/main/java/com/astro/mood/security/login/GoogleUserDetails.java
  src/main/java/com/astro/mood/security/login/LoginFilter.java
  src/main/java/com/astro/mood/security/login/OAuth2UserInfo.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/auth/CustomOauth2UserService.java
  src/main/java/com/astro/mood/service/exception/CustomException.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/service/s3Image/AwsS3Service.java
  src/main/java/com/astro/mood/web/advice/GlobalExceptionHandler.java
  src/main/java/com/astro/mood/web/controller/JwtLoginController.java
  src/main/java/com/astro/mood/web/controller/MainController.java
  src/main/java/com/astro/mood/web/dto/ApiResponse.java
  src/main/java/com/astro/mood/web/dto/ExceptionDto.java
  src/main/java/com/astro/mood/web/dto/auth/CustomUserInfoDto.java
  src/main/java/com/astro/mood/web/dto/auth/OauthProvider.java
  src/main/java/com/astro/mood/web/dto/auth/SignRequest.java
  src/main/java/com/astro/mood/web/dto/auth/UserRole.java
  src/main/java/com/astro/mood/web/interceptor/RequestTimeLoggingInterceptor.java
  src/main/java/com/astro/mood/web/interceptor/ResponseInterceptor.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/test/java/com/astro/mood/MoodApplicationTests.java
Labels: ⚙ Setting

#9 리액트 라우팅관련 웹컨피그 추가
  src/main/java/com/astro/mood/config/WebConfig.java
  src/main/java/com/astro/mood/web/controller/MainController.java
Labels: ⚙ Setting

#10 7 fe login
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/components/intro/KakaoLogin.jsx
  src/main/frontend/src/components/layout/ContentsArea.jsx
  src/main/frontend/src/components/layout/HeaderLayout.jsx
  src/main/frontend/src/components/layout/Layout.jsx
  src/main/frontend/src/images/about.png
  src/main/frontend/src/images/google_logo.png
  src/main/frontend/src/images/kakaotalk_small_logo.png
  src/main/frontend/src/index.js
  src/main/frontend/src/pages/AboutAll.jsx
  src/main/frontend/src/pages/AboutLogin.jsx
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/Intro.jsx
Labels: ✨ Feature

#14 12 fe pages
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/components/board/Comment.jsx
  src/main/frontend/src/components/button/WriteButton.jsx
  src/main/frontend/src/components/layout/ContentsArea.jsx
  src/main/frontend/src/components/layout/GlobalStyle.jsx
  src/main/frontend/src/components/layout/Header.jsx
  src/main/frontend/src/components/modal/ConfirmModal.jsx
  src/main/frontend/src/components/modal/Modal.jsx
  src/main/frontend/src/hooks/useUserActions.jsx
  src/main/frontend/src/index.css
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/Intro.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/WriteWorry.jsx
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#15 be jwtToken 생성
  src/main/frontend/src/App.js
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/data/repository/auth/UserTokenRepository.java
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/web/controller/GoogleLoginController.java
  src/main/resources/application.yaml
Labels: ✨ Feature

#16 11 feature be googlelogin
  src/main/frontend/public/favicon.ico
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/components/layout/Header.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/data/entity/user/User.java
  src/main/java/com/astro/mood/data/repository/auth/AuthRepository.java
  src/main/java/com/astro/mood/data/repository/auth/UserTokenRepository.java
  src/main/java/com/astro/mood/security/jwt/GoogleLoginFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/security/jwt/JwtToken.java
  src/main/java/com/astro/mood/security/login/CustomUserDetails.java
  src/main/java/com/astro/mood/security/login/LoginFilter.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/auth/CustomOauth2UserService.java
  src/main/java/com/astro/mood/service/auth/CustomUserDetailsService.java
  src/main/java/com/astro/mood/web/controller/GoogleLoginController.java
  src/main/java/com/astro/mood/web/controller/HelloWorldController.java
  src/main/java/com/astro/mood/web/dto/auth/UserRole.java
  src/main/resources/application.yaml
  src/main/resources/static/asset-manifest.json
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/main/resources/static/logo192.png
  src/main/resources/static/logo512.png
  src/main/resources/static/manifest.json
  src/main/resources/static/robots.txt
  src/main/resources/static/static/css/main.f855e6bc.css
  src/main/resources/static/static/css/main.f855e6bc.css.map
  src/main/resources/static/static/js/871.ecac38d0.chunk.js
  src/main/resources/static/static/js/871.ecac38d0.chunk.js.map
  src/main/resources/static/static/js/main.c2e08b91.js
  src/main/resources/static/static/js/main.c2e08b91.js.LICENSE.txt
  src/main/resources/static/static/js/main.c2e08b91.js.map
  src/main/resources/static/static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg
Labels: ⚙ Setting, ✨ Feature

#17 12 fe pages
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/components/board/PostContent.jsx
  src/main/frontend/src/components/board/PostTitle.jsx
  src/main/frontend/src/components/button/WriteButton.jsx
  src/main/frontend/src/components/calendar/Calendar.jsx
  src/main/frontend/src/components/comment/Comment.jsx
  src/main/frontend/src/components/comment/CommentInput.jsx
  src/main/frontend/src/components/comment/CommentList.jsx
  src/main/frontend/src/components/layout/ContentsArea.jsx
  src/main/frontend/src/components/layout/WhiteContentsArea.jsx
  src/main/frontend/src/components/write/Content.jsx
  src/main/frontend/src/components/write/ContentTitle.jsx
  src/main/frontend/src/components/write/EmotionSelector.jsx
  src/main/frontend/src/pages/DiaryCalendar.jsx
  src/main/frontend/src/pages/MyDiary.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/frontend/src/pages/WriteDiary.jsx
  src/main/frontend/src/pages/WriteWorry.jsx
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#18 11 feature be googlelogin
  src/main/frontend/public/logo192.png
  src/main/frontend/public/logo512.png
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/components/layout/Header.jsx
  src/main/java/com/astro/mood/data/entity/user/UserToken.java
  src/main/java/com/astro/mood/security/jwt/GoogleLoginFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/security/login/CustomOauth2UserDetails.java
  src/main/java/com/astro/mood/security/login/GoogleUserDetails.java
  src/main/java/com/astro/mood/service/auth/CustomOauth2UserService.java
  src/main/java/com/astro/mood/service/auth/CustomUserDetailsService.java
  src/main/java/com/astro/mood/web/controller/GoogleLoginController.java
  src/main/java/com/astro/mood/web/controller/MainController.java
Labels: ⚙ Setting, ✨ Feature

#25 BE - 유저정보 조회, 유저정보 수정
  src/main/java/com/astro/mood/security/login/CustomUserDetails.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/auth/CustomUserDetailsService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/service/s3Image/AwsS3Service.java
  src/main/java/com/astro/mood/web/advice/GlobalExceptionHandler.java
  src/main/java/com/astro/mood/web/controller/auth/UserController.java
  src/main/java/com/astro/mood/web/dto/auth/UserInfoRequest.java
  src/main/java/com/astro/mood/web/dto/auth/UserInfoResponse.java
Labels: ✨ Feature

#27 BE - 회원탈퇴
  src/main/java/com/astro/mood/data/repository/auth/AuthRepository.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/auth/CustomUserDetailsService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/web/advice/GlobalExceptionHandler.java
  src/main/java/com/astro/mood/web/controller/JwtLoginController.java
  src/main/java/com/astro/mood/web/controller/auth/UserController.java
Labels: 🔨 Refactor, ✨ Feature

#29 Feature/24 be worry
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/context/UserContext.jsx
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/service/worry/WorryService.java
  src/main/java/com/astro/mood/web/controller/worry/WorryController.java
  src/main/java/com/astro/mood/web/dto/worry/WorryDto.java
Labels: ✨ Feature, 📬 API

#28 FE - jwt 디코딩 추가
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/api/jwtDecode.js
  src/main/frontend/src/components/intro/GoogleLogin.jsx
Labels: ✨ Feature

#30 FE jwt디코딩을 통한 전역상태관리로 수정
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/context/UserContext.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
Labels: ✨ Feature

#31 BE - 좋아요 기능작업
  src/main/java/com/astro/mood/data/repository/likes/LikesRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/service/likes/LikesService.java
  src/main/java/com/astro/mood/web/controller/auth/UserController.java
  src/main/java/com/astro/mood/web/controller/likes/LikesController.java
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#32 일기 관련 엔티티 잘못된 부분 수정
  src/main/java/com/astro/mood/data/entity/diary/DiaryComment.java
  src/main/java/com/astro/mood/data/entity/diary/DiaryEmotion.java
Labels: ⚙ Setting

#33 FE 고민상세페이지 UI 변경
  src/main/frontend/src/components/board/WorryEditForm.jsx
  src/main/frontend/src/components/button/EditDeleteButton.jsx
  src/main/frontend/src/components/button/SmallButton.jsx
  src/main/frontend/src/components/dropdown/ResolveDropdown.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
Labels: 🎨 Html&css

#35 feature/fe,be-diary
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/components/board/DiaryEditForm.jsx
  src/main/frontend/src/components/board/PostContent.jsx
  src/main/frontend/src/components/calendar/Calendar.jsx
  src/main/frontend/src/components/write/EditEmotionSelector.jsx
  src/main/frontend/src/pages/MyDiary.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/frontend/src/pages/WriteDiary.jsx
  src/main/java/com/astro/mood/data/entity/diary/DiaryEmotion.java
  src/main/java/com/astro/mood/data/entity/emotion/Emotions.java
  src/main/java/com/astro/mood/data/repository/diary/DiaryEmotionRepository.java
  src/main/java/com/astro/mood/data/repository/diary/DiaryRepository.java
  src/main/java/com/astro/mood/service/diary/DiaryService.java
  src/main/java/com/astro/mood/web/controller/diary/DiaryController.java
  src/main/java/com/astro/mood/web/dto/diary/DiaryDto.java
Labels: ✨ Feature, 📬 API

#36 BE 댓글 CRUD, 고민댓글 신고, 비속어 필터링 적용
  build.gradle
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/data/entity/diary/DiaryComment.java
  src/main/java/com/astro/mood/data/entity/user/User.java
  src/main/java/com/astro/mood/data/entity/worry/WorryComment.java
  src/main/java/com/astro/mood/data/entity/worry/WorryCommentReport.java
  src/main/java/com/astro/mood/data/repository/diary/DiaryCommentRepository.java
  src/main/java/com/astro/mood/data/repository/diary/DiaryRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentReportsRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/comment/DiaryCommentService.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/service/wordFilter/BadwordFilterService.java
  src/main/java/com/astro/mood/service/wordFilter/ProfanityLoader.java
  src/main/java/com/astro/mood/service/wordFilter/Trie.java
  src/main/java/com/astro/mood/service/wordFilter/TrieNode.java
  src/main/java/com/astro/mood/web/controller/comment/CommentController.java
  src/main/java/com/astro/mood/web/controller/comment/WorryCommentController.java
  src/main/java/com/astro/mood/web/controller/likes/LikesController.java
  src/main/java/com/astro/mood/web/dto/comment/CommentRequest.java
  src/main/java/com/astro/mood/web/dto/comment/DiaryCommentResponse.java
  src/main/java/com/astro/mood/web/dto/comment/WorryCommentResponse.java
  src/main/resources/exceptionWords.json
  src/main/resources/profanities.json
Labels: ✨ Feature

#37 빌드시 경고 뜨는 부분 @Builder.Default 추가
  src/main/java/com/astro/mood/data/entity/worry/WorryComment.java
Labels: 🔨 Refactor

#40 12 fe pages
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/components/comment/Comment.jsx
  src/main/frontend/src/components/comment/CommentInput.jsx
  src/main/frontend/src/components/comment/CommentList.jsx
  src/main/frontend/src/components/comment/DiaryComment.jsx
  src/main/frontend/src/components/layout/Header.jsx
  src/main/frontend/src/components/main/EmotionAnalysis.jsx
  src/main/frontend/src/components/main/HappiestDay.jsx
  src/main/frontend/src/components/main/UniverseTemperature.jsx
  src/main/frontend/src/components/main/UserInfo.jsx
  src/main/frontend/src/context/UserContext.jsx
  src/main/frontend/src/images/profile.png
  src/main/frontend/src/pages/Main.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
Labels: 🎨 Html&css, 📬 API

#42 12 fe pages
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/components/main/EmotionAnalysis.jsx
  src/main/frontend/src/components/main/HappiestDay.jsx
  src/main/frontend/src/pages/Main.jsx
  src/main/frontend/src/pages/ModifyUser.jsx
Labels: 🎨 Html&css, 📬 API

#43 댓글 신고 검증부분 수정
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/service/wordFilter/ProfanityLoader.java
Labels: 🐞 BugFix, 🔨 Refactor

#44 BE SecurityConfig url 추가
  src/main/java/com/astro/mood/config/SecurityConfig.java
Labels: 🌏 Deploy

#45 BE - 댓글 목록에 유저의 좋아요 여부 표시
  src/main/frontend/src/components/comment/Comment.jsx
  src/main/java/com/astro/mood/data/repository/likes/LikesRepository.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/web/controller/comment/CommentController.java
  src/main/java/com/astro/mood/web/dto/comment/WorryCommentResponse.java
Labels: 🐞 BugFix

#46 FE - 유저정보 수정시 연락처 공란 일 때 수정, userContext 수정
  src/main/frontend/src/api/instance.js
  src/main/frontend/src/pages/ModifyUser.jsx
  src/main/java/com/astro/mood/data/entity/user/User.java
Labels: 🐞 BugFix

#47 12 fe pages
  src/main/frontend/src/components/board/PostContent.jsx
  src/main/frontend/src/components/board/PostTitle.jsx
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/MyDiary.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/java/com/astro/mood/web/controller/diary/DiaryController.java
  src/main/java/com/astro/mood/web/controller/worry/WorryController.java
Labels: 📬 API

#48 BE 사용자 리턴 메세지 변경
  src/main/frontend/src/api/api.js
  src/main/java/com/astro/mood/data/entity/user/User.java
  src/main/java/com/astro/mood/service/auth/AuthService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/web/controller/auth/UserController.java
Labels: 🔨 Refactor

#51 메인페이지 카운트 적용, 레벨 추가
  src/main/frontend/src/App.js
  src/main/frontend/src/api/api.js
  src/main/frontend/src/components/main/UniverseTemperature.jsx
  src/main/frontend/src/components/main/UserInfo.jsx
  src/main/frontend/src/images/levels/level_01.png
  src/main/frontend/src/images/levels/level_02.png
  src/main/frontend/src/images/levels/level_03.png
  src/main/frontend/src/images/levels/level_04.png
  src/main/frontend/src/images/levels/level_05.png
  src/main/frontend/src/images/levels/level_06.png
  src/main/frontend/src/images/levels/level_07.png
  src/main/frontend/src/images/levels/level_08.png
  src/main/frontend/src/images/levels/level_09.png
  src/main/frontend/src/images/levels/level_10.png
  src/main/frontend/src/pages/Main.jsx
  src/main/frontend/src/pages/ModifyUser.jsx
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
  src/main/java/com/astro/mood/data/entity/level/LevelThresholds.java
  src/main/java/com/astro/mood/data/entity/notice/Notice.java
  src/main/java/com/astro/mood/data/entity/user/User.java
  src/main/java/com/astro/mood/data/entity/worry/WorryComment.java
  src/main/java/com/astro/mood/data/repository/diary/DiaryRepository.java
  src/main/java/com/astro/mood/data/repository/level/LevelRepository.java
  src/main/java/com/astro/mood/data/repository/notice/NoticeRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
  src/main/java/com/astro/mood/service/auth/MainUserService.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/service/diary/DiaryService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/service/likes/LikesService.java
  src/main/java/com/astro/mood/service/notice/NoticeService.java
  src/main/java/com/astro/mood/web/controller/MainController.java
  src/main/java/com/astro/mood/web/controller/auth/MainUserController.java
  src/main/java/com/astro/mood/web/controller/comment/CommentController.java
  src/main/java/com/astro/mood/web/dto/auth/MainUserInfoResponse.java
  src/main/java/com/astro/mood/web/dto/comment/ReceiveWorryCommentResponse.java
  src/main/java/com/astro/mood/web/dto/comment/WorryCommentResponse.java
  src/main/java/com/astro/mood/web/dto/notice/NoticeType.java
Labels: 🎨 Html&css, 🔨 Refactor, ✨ Feature, 📬 API

#52 feature/be-emotionAnalysis
  src/main/java/com/astro/mood/data/entity/diary/DiaryEmotion.java
  src/main/java/com/astro/mood/data/entity/emotion/EmotionAnalysis.java
  src/main/java/com/astro/mood/data/repository/emotions/EmotionAnalysisRepository.java
  src/main/java/com/astro/mood/service/emotions/EmotionAnalysisService.java
  src/main/java/com/astro/mood/service/emotions/EmotionsService.java
  src/main/java/com/astro/mood/web/controller/emotions/EmotionAnalysisController.java
  src/main/java/com/astro/mood/web/controller/emotions/EmotionsController.java
  src/main/java/com/astro/mood/web/dto/emotions/EmotionDto.java
Labels: ✨ Feature

#54 FE 최근 일기 swiper 갯수 유지 기능 추가
  src/main/frontend/src/components/main/HappiestDay.jsx
Labels: ✨ Feature

#55 FE 받은 답변 페이지 작업
  src/main/frontend/src/components/main/UserInfo.jsx
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/web/dto/comment/ReceiveWorryCommentResponse.java
Labels: 🎨 Html&css, 📬 API

#56 FE 보낸 답변 페이지 작업
  src/main/frontend/src/api/api.js
  src/main/frontend/src/pages/AnswerWorryBoard.jsx
  src/main/frontend/src/pages/ModifyUser.jsx
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
Labels: 🎨 Html&css, 📬 API

#57 FE modalContext 적용
  src/main/frontend/src/App.js
  src/main/frontend/src/components/modal/AllModal.jsx
  src/main/frontend/src/context/ModalContext.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/frontend/src/pages/WriteDiary.jsx
  src/main/frontend/src/pages/WriteWorry.jsx
Labels: ✨ Feature

#61 FE a태그 빌드 경고 부분 button으로 변경
  src/main/frontend/src/components/main/UniverseTemperature.jsx
  src/main/frontend/src/components/main/UserInfo.jsx
  src/main/frontend/src/pages/AnswerWorryBoard.jsx
  src/main/frontend/src/pages/ModifyUser.jsx
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
Labels: 🔨 Refactor

#62 FE a태그 빌드 경고 부분 button으로 변경-주석 삭제
  src/main/frontend/src/components/main/UniverseTemperature.jsx
  src/main/frontend/src/pages/AnswerWorryBoard.jsx
Labels: 🎨 Html&css
