Repository astro-mood/FS, pull requests merged in 2025-02, with the labels that each got.

#63 FE 댓글수정 commentInput 적용
  src/main/frontend/src/components/comment/Comment.jsx
  src/main/frontend/src/components/comment/CommentInput.jsx
  src/main/frontend/src/components/comment/DiaryComment.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
Labels: 🎨 Html&css

#64 12 fe pages
  src/main/frontend/src/components/intro/AstromoodGuide.jsx
  src/main/frontend/src/components/intro/GoogleLogin.jsx
  src/main/frontend/src/components/intro/KakaoLogin.jsx
  src/main/frontend/src/pages/AboutAll.jsx
  src/main/frontend/src/pages/AboutLogin.jsx
  src/main/frontend/src/pages/Intro.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/security/jwt/KakaoLoginFilter.java
Labels: ✨ Feature

#65 커서기반 스크롤페이징 적용
  src/main/frontend/src/api/api.js
  src/main/frontend/src/components/comment/Comment.jsx
  src/main/frontend/src/pages/AnswerWorryBoard.jsx
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/frontend/src/pages/MyWorry.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/java/com/astro/mood/data/repository/diary/DiaryCommentRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
  src/main/java/com/astro/mood/data/repository/worry/WorryRepository.java
  src/main/java/com/astro/mood/service/comment/DiaryCommentService.java
  src/main/java/com/astro/mood/service/comment/WorryCommentService.java
  src/main/java/com/astro/mood/service/worry/WorryService.java
  src/main/java/com/astro/mood/web/controller/comment/CommentController.java
  src/main/java/com/astro/mood/web/controller/worry/WorryController.java
  src/main/java/com/astro/mood/web/dto/PaginatedResponse.java
  src/main/java/com/astro/mood/web/dto/comment/WorryCommentResponse.java
Labels: 🎨 Html&css, 🔨 Refactor, ✨ Feature, 📬 API

#66 보낸답변/받은답변 조건 수정
  src/main/java/com/astro/mood/data/repository/worry/WorryCommentRepository.java
Labels: 🔨 Refactor

#67 카카오 로그인 작업중
  src/main/java/com/astro/mood/data/repository/auth/AuthRepository.java
  src/main/java/com/astro/mood/security/jwt/JWTFilter.java
  src/main/java/com/astro/mood/security/jwt/JWTUtil.java
  src/main/java/com/astro/mood/security/jwt/KakaoLoginFilter.java
  src/main/java/com/astro/mood/service/auth/CustomUserDetailsService.java
  src/main/java/com/astro/mood/service/exception/ErrorCode.java
  src/main/java/com/astro/mood/web/dto/auth/KakaoUserDto.java
  src/main/resources/application.yaml
Labels: 🙋‍♂️ Question, ✨ Feature

#68 카카오 로그인/로그아웃 수정
  src/main/frontend/src/App.js
  src/main/frontend/src/components/intro/KakaoLogin.jsx
  src/main/frontend/src/components/layout/Header.jsx
  src/main/frontend/src/pages/KakaoLoginCallback.jsx
  src/main/java/com/astro/mood/config/SecurityConfig.java
  src/main/java/com/astro/mood/security/jwt/KakaoLoginFilter.java
  src/main/java/com/astro/mood/security/jwt/OauthLoginFilter.java
Labels: 🔨 Refactor, 📬 API

#69 고민리스트 페이지 높이 조절
  src/main/frontend/src/pages/BoardWorry.jsx
  src/main/java/com/astro/mood/service/wordFilter/BadwordFilterService.java
Labels: 🎨 Html&css, 🐞 BugFix

#70 FE 에러 메시지 적용
  src/main/frontend/src/images/about.png
  src/main/frontend/src/pages/AboutAll.jsx
  src/main/frontend/src/pages/OthersWorry.jsx
  src/main/frontend/src/pages/ViewDiary.jsx
  src/main/frontend/src/pages/WriteDiary.jsx
  src/main/frontend/src/pages/WriteWorry.jsx
  src/main/java/com/astro/mood/service/worry/WorryService.java
Labels: 🎨 Html&css, ✨ Feature

#71 FE intro credit 추가
  src/main/frontend/src/pages/Intro.jsx
Labels: 🎨 Html&css

#72 카카오 로그인 콘솔로그 제거
  src/main/frontend/src/pages/KakaoLoginCallback.jsx
Labels: 🔨 Refactor

#73 스크롤페이징 기본 세팅 20개로 변경
  src/main/frontend/src/api/api.js
  src/main/frontend/src/pages/ReceiveAnswerWorryBoard.jsx
Labels: 📬 API

#74 Update README.md
  README.md
Labels: 📃 Docs
